hbeni/fgcom-mumble

server/fgcom-radio-playback.bot.lua
=> Added notification to new joined users to radio-playback-bot

client/mumble-plugin/fgcom-mumble.cpp, client/mumble-plugin/lib/globalVars.h, client/mumble-plugin/lib/plugin_io.cpp, client/mumble-plugin/lib/plugin_io.h, client/plugin.spec.md, server/fgcom-radio-playback.bot.lua, server/sharedFunctions.inc.lua, server/test/fgcom-echo.bot.lua, server/test/fgcom-fakepilot.bot.lua, server/test/fgcom-spamPluginData.bot.lua, server/test/pluginSendtest.lua
Implement bandwith trottle for location updates
(resolves #10 )
=> Issue10 bandwith trottle

server/fgcom-botmanager.sh
Added a watchdog to the botmanager:
- restarting died status- and recorder bots
- killing the bots if botmanager is terminating
=> Implement botmanager watchdog

client/mumble-plugin/fgcom-mumble.cpp, client/mumble-plugin/lib/io_UDPServer.cpp, client/mumble-plugin/lib/radio_model.cpp, client/mumble-plugin/lib/radio_model.h, client/mumble-plugin/lib/radio_model_hf.cpp, client/mumble-plugin/lib/radio_model_string.cpp, client/mumble-plugin/lib/radio_model_uhf.cpp, client/mumble-plugin/lib/radio_model_vhf.cpp, client/mumble-plugin/makefile, client/mumble-plugin/test/frqtest.cpp, client/mumble-plugin/test/geotest.cpp, client/mumble-plugin/test/test_setup.sh, client/plugin.spec.md
- Refactoring radio model implementation to be object oriented
- Added very simple HF and UHF radio model
=> Refactor radio model implementation

.gitmodules, README-de_DE.md, README.md, client/mumble-plugin/fgcom-mumble.cpp, client/mumble-plugin/lib/fgcom-mumble.h, client/mumble-plugin/lib/http/httplib.h, client/mumble-plugin/lib/json/json.hpp, client/mumble-plugin/lib/updater.cpp, client/mumble-plugin/makefile
=> Implement mumble autoupdater

client/fgfs/Protocol/fgcom-mumble.xml, client/mumble-plugin/fgcom-mumble.cpp, client/mumble-plugin/lib/debug.cpp, client/mumble-plugin/lib/globalVars.h, client/mumble-plugin/lib/io_UDPServer.cpp, client/mumble-plugin/lib/radio_model.cpp, client/mumble-plugin/lib/radio_model.h, client/mumble-plugin/lib/radio_model_hf.cpp, client/mumble-plugin/lib/radio_model_string.cpp, client/mumble-plugin/lib/radio_model_uhf.cpp, client/mumble-plugin/lib/radio_model_vhf.cpp, client/mumble-plugin/test/25_833-test.sh, client/mumble-plugin/test/frqtest.cpp, client/plugin.spec.md
=> Better channel spacing

client/mumble-plugin/fgcom-mumble.cpp, client/mumble-plugin/lib/debug.cpp, client/mumble-plugin/lib/garbage_collector.cpp, client/mumble-plugin/lib/garbage_collector.h, client/mumble-plugin/lib/io_UDPClient.cpp, client/mumble-plugin/lib/io_UDPClient.h, client/mumble-plugin/lib/io_UDPServer.cpp, client/mumble-plugin/lib/io_UDPServer.h
=> Fix segfault: mumble_shutdown() not waiting for threads finishing

Readme.architecture.md, client/mumble-plugin/fgcom-mumble.cpp, client/mumble-plugin/fgcom-mumble.ini, client/mumble-plugin/lib/debug.cpp, client/mumble-plugin/lib/globalVars.h, client/mumble-plugin/lib/io_UDPClient.cpp, client/mumble-plugin/lib/io_UDPServer.cpp, client/mumble-plugin/lib/io_plugin.cpp, client/plugin.spec.md, client/radioGUI/src/main/java/hbeni/fgcom_mumble/UDPclient.java, client/radioGUI/src/main/java/hbeni/fgcom_mumble/gui/OptionsWindow.form, client/radioGUI/src/main/java/hbeni/fgcom_mumble/gui/OptionsWindow.java, client/radioGUI/src/main/java/hbeni/fgcom_mumble/radioGUI.java
- Adds support for retrieving UDP packets from remote places
- Adds support for answering RDF-messages to the network
=> Remote host

client/mumble-plugin/fgcom-mumble.cpp, client/mumble-plugin/fgcom-mumble.ini, client/mumble-plugin/lib/debug.cpp, client/mumble-plugin/lib/globalVars.h, client/mumble-plugin/lib/io_UDPServer.cpp, client/mumble-plugin/lib/io_plugin.cpp, client/mumble-plugin/lib/io_plugin.h, client/mumble-plugin/makefile
This PR fixes plugin loading and running errors on windows10.
=> Fix #66 (make windows build work)

client/radioGUI/src/main/java/hbeni/fgcom_mumble/gui/MainWindow.form, client/radioGUI/src/main/java/hbeni/fgcom_mumble/gui/MainWindow.java
Not an important fix, just something that bugs me when I'm testing.
=> Fix Simple Typo

.github/workflows/codeql-analysis.yml, client/mumble-plugin/makefile
Fix #68 
Test build:
- [fgcom-mumble-x86_32.zip](https://github.com/hbeni/fgcom-mumble/files/6049100/fgcom-mumble-x86_32.zip)
- from plugin commit 2c7b9a5
- against mumble commit deb74a6 azure build from 05.02.2020
=> Add 32bit build

README-de_DE.md, README.md, client/fgfs/Readme.md, client/fgfs/addon-config.xml, client/fgfs/addon-main.nas, client/fgfs/addon-menubar-items.xml, client/fgfs/addon-metadata.xml, client/fgfs/gui/dialogs/fgcom-mumble-settings.xml
=> FlightGear Addon

client/mumble-plugin/fgcom-mumble.cpp, client/mumble-plugin/fgcom-mumble.h, client/mumble-plugin/src/fgcom_stateManager.cpp
@hbeni Something like this?
This basically adds another layer to manage fgcom_identity instances outside of the main plugin class. I should allow us to implement more user management functions witthout cluttering up the main plugin class.
No other functionallity in the plugin has been added although several functions recieved better documentation.
=> Initial fgcom_stateManger implemetation.

.github/workflows/make-release.yml, README-de_DE.md, README.md
The g++-10 version did not load anymore
=> MacOS Github build switch g++10 -> g++11

.github/workflows/make-release.yml, README-de_DE.md, README.md, client/mumble-plugin/Makefile
Simplifies makefiles and adds new shortcut for macOS native builds
=> Makefile simplifications

server/fgcom-radio-playback.bot.lua
This supports fixed and random time intervals:
```
--pause=<s>          pause for <s> seconds
--pause=<min>,<max>  pause for at least <min> and at most <max> seconds,
randomly choosen at each iteration
```
fix #155
=> Server: Replay-bot now supports --pause option to sleep between looped samples

.github/workflows/make-release.yml
For intermediary release 1.2. with openssl 1.1 on linux
=> Build set to ubuntu-20.04, so we get a build against openssl 1.1

.github/workflows/codeql-analysis.yml
Adds sytnax checking for 
- PHP statuspage
- lua bots
=> CodeQL: Add syntax checking for php and lua

server/statuspage/config.dist.ini, server/statuspage/fgcom-status.bot.lua
New startup config option --purge to be able to adjust the purge interval of stale entries
New support for chat commands to change the purge interval in realtime
Fix #181
(cherry picked)
=> Server/Statusbot: add config options and chat commands

server/VERSION, server/statuspage/Readme.statuspage.md, server/statuspage/config.dist.ini, server/statuspage/fgcom-status.bot.lua, server/statuspage/inc/index.tpl, server/statuspage/inc/style.css, server/statuspage/index.php
=> Issue 198 add mumble url

client/fgfs-addon/FGData/Protocol/fgcom-mumble.xml, client/fgfs-addon/Readme.md, client/fgfs-addon/addon-main.nas, client/fgfs-addon/addon-metadata.xml, client/fgfs-addon/gui/dialogs/fgcom-mumble-comoverride.xml, client/fgfs-addon/gui/dialogs/fgcom-mumble-settings.xml, client/fgfs-addon/radios.nas
=> Fgfs addon radio enhancements

client/fgfs-addon/addon-main.nas
Running FGCom-mumble and legacy FGCom has resulted in legacy FGCom segfaulting. So, if we activate FGCom-mumble, legacy FGCom must be turned off.
Fix #204
(and indirectly fix #203)
=> FGFS-Addon: disable FGCom when enabling FGCom-mumble
