README.md
Readme.architecture.md
client/fgfs/Protocol/fgcom-mumble.xml
client/mumble-plugin/fgcom-mumble.cpp
client/mumble-plugin/lib/debug.cpp
client/mumble-plugin/lib/garbage_collector.cpp
client/mumble-plugin/lib/garbage_collector.h
client/mumble-plugin/lib/globalVars.h
client/mumble-plugin/lib/plugin_io.cpp
client/mumble-plugin/lib/plugin_io.h
client/mumble-plugin/lib/radio_model.cpp
client/mumble-plugin/lib/radio_model.h
client/mumble-plugin/lib/rdfUDP.cpp
client/mumble-plugin/lib/rdfUDP.h
client/mumble-plugin/makefile
client/plugin.spec.md
server/fgcom-botmanager.sh
server/fgcom-radio-playback.bot.lua
server/fgcom-radio-recorder.bot.lua
server/sharedFunctions.inc.lua
server/statuspage/fgcom-status.bot.lua
server/test/fgcom-echo.bot.lua
server/test/fgcom-fakepilot.bot.lua
server/test/fgcom-spamPluginData.bot.lua
server/test/pluginSendtest.lua

Multi identity support for plugin instances.
With this, a mumble plugin instance can handle different identities. Each identity has its own set of user data (callsign, location) and radio stacks.
This is mainly useful for ATC clients (like ATC-Pie) that want to manage different locations in a single mumble and single ATC application instance.
(Resolves #28)

Multi identity support

---

.gitignore
README.md
client/fgfs/Protocol/fgcom-mumble.xml
client/mumble-plugin/fgcom-mumble.cpp
client/mumble-plugin/lib/garbage_collector.cpp
client/mumble-plugin/lib/globalVars.h
client/mumble-plugin/lib/plugin_io.cpp
client/mumble-plugin/lib/radio_model.cpp
client/mumble-plugin/lib/radio_model.h
client/mumble-plugin/lib/rdfUDP.cpp
client/mumble-plugin/makefile
client/mumble-plugin/test/frqtest.cpp
client/mumble-plugin/test/genAllFrq.sh
client/mumble-plugin/test/test_setup.sh
client/plugin.spec.md
server/fgcom-botmanager.sh
server/fgcom-radio-playback.bot.lua
server/fgcom-radio-recorder.bot.lua

- Switch plugin to use real carier wave frequencies internally
- 8.33 / 25kHz parsing support for numeric frequencies
- UDP input interface will now convert
Implements #34

Implement 8.33/25kHz parsing support (implements #34)

---

client/mumble-plugin/lib/io_UDPServer.cpp
client/mumble-plugin/lib/radio_model.h
client/mumble-plugin/lib/radio_model_hf.cpp
client/mumble-plugin/lib/radio_model_string.cpp
client/mumble-plugin/lib/radio_model_uhf.cpp
client/mumble-plugin/lib/radio_model_vhf.cpp
client/mumble-plugin/test/frqtest.cpp
client/mumble-plugin/test/genAllFrq.sh

- added a new conv_freq2chan() method to radio models
They convert a given real wave frequency to a channel alias (thats different for 8.33 channels)
ATC-Pie and mumble-plugin clients now transmit the channel name instead of the tuned real carrier frequency, so its more usable for people to tune into known used frequencies.
Fix #61

Show channels instead of real wave frequency, if possible

---

client/fgfs/Protocol/fgcom-mumble.xml
client/mumble-plugin/lib/radio_model_vhf.cpp
client/mumble-plugin/test/genAllFrq.sh

- changed frq property to standard one
- disabled transmission of the second "real-frq" property
- corrected parsing of frq field for shortened decimal representations:
FGFS may short the 118.100 to 118.1 which yielded wrongly "118.1" as real frequency.
It is a valid 8.33 channel tough and must return "118.0083".
Fix #71

Fix #71 short frq parsing bug; change to FGFS protocol

---

client/mumble-plugin/fgcom-mumble.cpp
client/mumble-plugin/lib/io_plugin.cpp

Fix #81 memleaks

---

client/mumble-plugin/fgcom-mumble.cpp
client/mumble-plugin/lib/debug.cpp
client/mumble-plugin/lib/io_UDPServer.cpp
client/mumble-plugin/lib/io_plugin.cpp
client/mumble-plugin/lib/radio_model.h
client/plugin.spec.md
server/sharedFunctions.inc.lua
server/statuspage/Readme.statuspage.md
server/statuspage/fgcom-status.bot.lua
server/statuspage/inc/style.css
server/statuspage/index.php

- UDP-server recalculates radio's operable state flag
- Plugin-io protocol now transmitts operable state flag to remote plugins (protcol field `COMn_OPR`)
- Lua common library parses OPR field
- Statusbot writes complete radio state to the web-db now (instead of just the frequency)
- Status web page displays inop radios in list and popups in different color now

Include radio operable state in protocol

---

client/fgfs-addon/FGData/Protocol/fgcom-mumble.xml
client/fgfs-addon/addon-main.nas
client/mumble-plugin/fgcom-mumble.cpp
client/mumble-plugin/lib/io_UDPClient.cpp
client/mumble-plugin/lib/io_UDPClient.h
client/plugin.spec.md

Add support for `comm[2]`, which is used by a few aircraft: A320, A330, B777 (in my case, it's to add one to the Viggen).
There's also a typo fix for `COM2_SQC`.
As far as I can tell the mumble plugin doesn't need any change, can you confirm?
I gave it a quick test, everything seems to work, including the UI (mumble message and fgcom-mumble status webpage show the additional frequency, but only if it exists).
Also, would you like me to ~~copy paste some more~~ add more radios while I'm at it?
I'm not aware of aircrafts using `comm[3]`, but I haven't done a throughout check.
I also didn't add more ADFs because I think the mumble plugin -> FGFS direction needs to be adapted (on the plugin side).

Add COM3 (comm[2]) radio to FG protocol

---

README-de_DE.md
README.md

Add info to readmes that the plugin can be installed by double-clicking usually.

Doc addition: installing per double-click

---

.gitignore
client/mumble-plugin/Makefile

- DLLs now have additional infos in the file details header.
- Added a new "mingwprefix" Makefile variable, so it's easier to switch target platforms
without to need to change the actual compiler. This also allows us to reuse the prefix
for compilation of the dll resource file.
(closes #142)

Plugin: Windows builds add DLL infos

---

client/mumble-plugin/Makefile
client/mumble-plugin/fgcom-mumble.cpp
client/mumble-plugin/fgcom-mumble.h
client/mumble-plugin/lib/audio.cpp
client/mumble-plugin/lib/audio.h
client/mumble-plugin/lib/debug.cpp
client/mumble-plugin/lib/garbage_collector.cpp
client/mumble-plugin/lib/io_plugin.cpp
client/mumble-plugin/lib/radio_model.cpp
client/mumble-plugin/lib/radio_model.h
client/mumble-plugin/lib/radio_model_hf.cpp
client/mumble-plugin/lib/radio_model_string.cpp
client/mumble-plugin/lib/radio_model_uhf.cpp
client/mumble-plugin/lib/radio_model_vhf.cpp
client/mumble-plugin/test/geotest.cpp

Plugin: refactored audio filters to be model specific
The previously global audio filters are now part of the radio model.
Now we can define different audio filter characteristics for different radio models.
This also made the mumble_onAudioSourceFetched a little less long and a little more generic.

Restructure audio callback

---

server/fgcom-radio-recorder.bot.lua
server/sharedFunctions.inc.lua

Previously we assumed (hardcoded) the default recording speed of 0.02 (mumbles default).
This resulted in crippled recordings for mumbles "audio per packet" values 10, 40 and 60.
Now, the samples are inspected regarding their spacing when they are received from the recorder bot.
Also, the FGCS file header is now written at recording closing time, so we can easily add the calculated value.
The calculation records all sample delays and then takes the average of them, rounded to the nearest tenth,
to smooth out jitter (also the first and last sample seem to be "0" delay most of the time)
Also, a math.average() function has been added to the sharedFunctios lib in case lua doesn't bring its own.
Fix #152

Server: samples recording speed is deduced now

---

client/fgfs-addon/FGData/Protocol/fgcom-mumble.xml
client/fgfs-addon/addon-main.nas
client/fgfs-addon/addon-metadata.xml
client/fgfs-addon/gui/combar.nas
client/fgfs-addon/radios.nas

The Protocol file hard codes up to 4 Radios+2 ADF currently.
It would be good to dynamicalize this, so the UDP string is created on the fly.

FGFS Addon: Basic rewrite to dynamically registering radios

---

client/fgfs-addon/FGData/Protocol/fgcom-mumble.xml
client/fgfs-addon/Readme.md
client/fgfs-addon/addon-main.nas
client/fgfs-addon/addon-metadata.xml
client/fgfs-addon/gui/combar.nas
client/fgfs-addon/intercom.nas
client/fgfs-addon/radios.nas

Adds intercom support for use in FGFS copilot mode.
Intercom functionality is automatically enabled when you make a connection using the FGFS copilot module.

FGFS Addon: Intercom support

---

client/mumble-plugin/lib/radio_model.h

Compilation of the mumble plugin fails with g++13.
The error was:
`  lib/radio_model.h:176:99: error: ‘uint32_t’ has not been declared`
Fix is to "`#include <cstdint>`"

mumble-plugin: Fix for gcc-13 build failure

---

.gitmodules
client/mumble-plugin/fgcom-mumble.cpp
client/mumble-plugin/fgcom-mumble.h
client/mumble-plugin/fgcom-mumble.ini
client/mumble-plugin/lib/globalVars.h
client/mumble-plugin/lib/updater.cpp
client/mumble-plugin/test/updater-test.cpp
server/VERSION
server/statuspage/version.php

This adds:
- a new non-ssl updater.
It can be invoked by:
- don't build with openssl support (`make .... SSLFLAGS= ....`)
(_with_ openSSL support compiled, the github ssl secured web release page is still the default source used by the updater)
- set the new ini file variable `updaterURL` to a url
The default url which is used for the non-ssl build is http://fgcom.hallinger.org/version.php (which is also newly supplied for the server part, see below)
- There is also a new plugin client updater test tool in the tools dir, but it's not built by default.
- The server part was enhanced by a new `version.php` file, that hardcoded fetches and prepares the version info for the plugin based on the github release info.
It is intended to be served with http only for that purpose.
This way, we …

No ssl updater

---

client/fgfs-addon/addon-main.nas
client/fgfs-addon/addon-metadata.xml
client/fgfs-addon/gui/dialogs/fgcom-mumble-settings.xml

Due to the structural changes, the addon is not compatible with current stable FGFS (2020.3). You need at least 2024.1.

FGFS-addon: Compatibility issues

---

client/fgfs-addon/Readme.md
client/fgfs-addon/addon-main.nas
client/fgfs-addon/gui/dialogs/fgcom-mumble-settings.xml

Can be disabled from commandline: `--prop:bool:/addons/by-id/org.hallinger.flightgear.FGCom-mumble/check-for-updates=0`
Setting is persistent.
Manual check is possible trough setting dialog.

FGFS-Addon: Add option to disable update-check

---

client/fgfs-addon/addon-main.nas
client/fgfs-addon/gui/dialogs/fgcom-mumble-debug.xml
client/fgfs-addon/gui/dialogs/fgcom-mumble-settings.xml
client/fgfs-addon/radios.nas

COM now will request RDF data from the plugin and use it to set a new `/instrumentation/comm[n]/receiving-flag_fgcom-mumble`.
Fix #209

FGFS-Addon: Add RDF capabilities to COM devices

---

Makefile
client/fgfs-addon/FGData/Protocol/fgcom-mumble.xml
client/fgfs-addon/addon-main.nas
client/fgfs-addon/gui/dialogs/fgcom-mumble-settings.xml
client/mumble-plugin/fgcom-mumble.cpp
client/mumble-plugin/fgcom-mumble.h
client/mumble-plugin/fgcom-mumble.ini
client/mumble-plugin/lib/globalVars.h
client/mumble-plugin/lib/io_UDPServer.cpp
client/plugin.spec.md
client/radioGUI/pom.xml
client/radioGUI/src/main/java/hbeni/fgcom_mumble/UDPclient.java
client/radioGUI/src/main/java/hbeni/fgcom_mumble/gui/OptionsWindow.form
client/radioGUI/src/main/java/hbeni/fgcom_mumble/gui/OptionsWindow.java
client/radioGUI/src/main/java/hbeni/fgcom_mumble/radioGUI.java

Adds an option to make the plugin handle PTT requests from clients to handle mumbles PTT even if the plugin is not active.
This allows users to use their sim's PTT-button to enable mumbles PTT even in ordinary channels.
Fix #222

Issue 222: Add PTT handling if plugin not active

---

client/mumble-plugin/fgcom-mumble.cpp
client/mumble-plugin/fgcom-mumble.h
client/mumble-plugin/lib/globalVars.h

The change in signal quality will now be interpolated over 500ms, so fast moving entities will not show stepped audio output.
Fix #217

Client/Plugin: Time based interpolator for signal quality

---

.github/workflows/make-release.yml
Makefile
client/mumble-plugin/Makefile
client/mumble-plugin/fgcom-mumble.cpp

Mumble does not officially support Apple Silicon (`arm64`) yet, but it runs relatively well under emulation using Rosetta (`x86_64`). This commit builds a "Fat Universal" binary, that contains the plugin for both architectures, so that the same plugin can work both under native Mumble (if someone self-builds Mumble), and emulated Mumble (if someone installs it the usual way).

Build Universal (`arm64`+`x86_64`) mumble plugin
